apiVersion: apps/v1
kind: Deployment
metadata:
  name: vectorizer
  namespace: iplus
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app.kubernetes.io/name: vectorizer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vectorizer
    spec:
      containers:
      - name: vectorizer
        image: example-image #docker.hasti.co/iplus/api:developer
        imagePullPolicy: Always
        resources:
          requests:
            memory: "0.5Gi"
            cpu: "0.1"
          limits:
            memory: "2Gi"
            cpu: "1"
        ports:
        - containerPort: 50051
      restartPolicy: Always
