apiVersion: v1
data:
  policy.csv: |
    p, role:none, *, *, */*, deny
    g, rxgroup, role:admin
    g, adminchange, role:admin
  policy.default: role:none
  scopes: '[groups, uid]'
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: argo-cd
    meta.helm.sh/release-namespace: argocd
  creationTimestamp: "2023-09-03T05:22:10Z"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v2.8.1
    helm.sh/chart: argo-cd-5.43.5
  name: argocd-rbac-cm
  namespace: argocd
