version: '3.8'

services:
  minio-sync-app:
    image: docker.hasti.co/minio/minio-sync:latest
    container_name: minio-sync-container
    ports:
      - "5000:5000"
    environment:
      - APP_NAME=MinIO Sync Webhook
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - PORT=5000
      - MATTERMOST_WEBHOOK_URL=${MATTERMOST_WEBHOOK_URL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data:/data
    restart: unless-stopped
    networks:
      - data_default

networks:
  data_default:
    external: true
