apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    serviceMonitorSelector: prometheus
  name: prometheus
  namespace: monitoring
spec:
  endpoints:
  - interval: 120s
  namespaceSelector: {}
  selector:
    matchLabels: {}
