apiVersion: v1
kind: Service
metadata:
  name: flowbridge-adminapi
  namespace: develop
spec:
  ports:
    - port: 80
      targetPort: 80
      name: api
  selector:
    app.kubernetes.io/name: flowbridge-adminapi