apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rabbit-scaledobject
  namespace: monitoring
spec:
  scaleTargetRef:
    name: nginx-deployment
    apiVersion: apps/v1
    kind: Deployment
  pollingInterval: 15
  idleReplicaCount: 0
  minReplicaCount: 1
  maxReplicaCount: 5
  cooldownPeriod: 30
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 60
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15            
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://thanos-querier.monitoring.svc.cluster.local:9090  # Change this to the Prometheus service address
        metricName: rabbitmq_queues
        query: rabbitmq_queues{kubernetes_namespace="test"}
        threshold: '30'  # Scale if the metric is greater than this value

