---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-hasti-sentiment
  namespace: test
  labels:
    app.kubernetes.io/name: chatbot-hasti-sentiment
    image-tag: "@build_number"

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: chatbot-hasti-sentiment
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

  template:
    metadata:
      labels:
        app.kubernetes.io/name: chatbot-hasti-sentiment
        image-tag: "@build_number"
    spec:
      imagePullSecrets:
        - name: hasti-docker-repo
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: "app.kubernetes.io/name"
                  operator: In
                  values:
                    - chatbot-hasti-sentiment
              topologyKey: "kubernetes.io/hostname" 
      containers:
        - image: docker.hasti.co/alpha/hasti-sentiment:test
          imagePullPolicy: Always
          name: hasti-sentiment
          env:
            - name: PORT
              value: "80"
            - name: MULTI_MODEL_PATH
              value: /app/multi
            - name: BINARY_MODEL_PATH
              value: /app/binary
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-hasti-sentiment-svc
  namespace: test
spec:
  selector:
    app.kubernetes.io/name: chatbot-hasti-sentiment
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: chatbot-hasti-sentiment
    namespace: test
spec:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: chatbot-hasti-sentiment
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80 

