FROM docker.hasti.co/library/golang:1.21-alpine3.18 AS builder
WORKDIR /app

ENV http_proxy=http://172.31.58.242:1081
ENV https_proxy=http://172.31.58.242:1081

#RUN apk update && apk add curl && curl --version

ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.cn,direct


#RUN apk --no-cache add ca-certificates

COPY go.mod go.sum ./

RUN  go mod download


COPY . .

RUN go build -o main .

#RUN CGO_ENABLED=0 GO111MODULE=on go build -v -o main -installsuffix cgo -ldflags="-w -s" ./*.go

#RUN go build -o main main.go

FROM docker.hasti.co/library/alpine:3.18
WORKDIR /app
COPY --from=builder /app/main .
#COPY --from=builder /app .
COPY db/migration ./db/migration

#RUN useradd -u 10001 user1 && groupadd group1  &&  chown -R user1:group1 /app
#USER user1:group1

CMD [ "/app/main" ]

