apiVersion: v1
kind: Service
metadata:
  name: api-search
  namespace: iplus
spec:
  selector:
    app.kubernetes.io/name: api
  ports:
  - name: http
    protocol: TCP
    port: 3001
    targetPort: 3001