---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: chatbot-hasti-nsfw
    namespace: main
spec:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: chatbot-hasti-nsfw
    minReplicas: 1
    maxReplicas: 3
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 90
          type: Utilization
