apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer
  namespace: iplus
  #annotations:
  #  configmap.reloader.stakater.com/reload: "my-configmap"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app.kubernetes.io/name: indexer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: indexer
    spec:
      containers:
      - name: indexer
        image: example-image #docker.hasti.co/iplus/api:developer
        imagePullPolicy: Always
        resources:
          requests:
            memory: "0.5Gi"
            cpu: "0.1"
          limits:
            memory: "2Gi"
            cpu: "1"
        ports:
        - containerPort: 3001
        #envFrom:
        #- configMapRef:
        #    name: my-configmap
      restartPolicy: Always
