---
apiVersion: v1
kind: Secret
metadata:
  namespace: monitoring
  name: objstore
  labels:
    app.kubernetes.io/name: receiver
type: Opaque
stringData:
  objstore.yml: |-
    type: S3
    config:
      bucket: stage
      endpoint: ""
      region: "us-east-1"
      access_key: ""
      secret_key: ""
