{{- if .Values.alertmanager.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: {{ .Values.namespace }}
  labels:
    app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
      annotations:
        checksum/alertmanager-config.yaml: {{ include (print $.Template.BasePath "/alertmanager-configmap.yaml") . | sha1sum }}
    spec:
{{- if index .Values "alertmanager" "affinity" "enabled" }}      
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: environment
                operator: In
                values:
                - monitoring
{{- end }}                  
      containers:
      - name: alertmanager
        image: docker.hasti.co/prom/alertmanager:v0.28.1 #{{ .Values.alertmanager.image }}
        args:
          - '--config.file=/etc/alertmanager/config.yml'
          - '--storage.path=/alertmanager'
        ports:
        - name: alertmanager
          containerPort: 9093
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager
        - name: alertmanager
          mountPath: /alertmanager
        - name: timezone-volume
          mountPath: /etc/timezone
          readOnly: true
        - name: localtime-volume
          mountPath: /etc/localtime
          readOnly: true            
      volumes:
      - name: config-volume
        configMap:
          name: alertmanager
      - name: alertmanager
        emptyDir: {}
      - name: timezone-volume
        hostPath:
          path: /etc/timezone
          type: File
      - name: localtime-volume
        hostPath:
          path: /etc/localtime
          type: File
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
  labels:
    name: alertmanager
  name: alertmanager
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: alertmanager
  type: {{ .Values.alertmanager.service.type }}
  ports:
  - name: alertmanager
    protocol: TCP
    port: 9093
    targetPort: 9093
{{- end }}
