---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: cms-webapi
    namespace: develop
spec:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: cms-webapi
    minReplicas: 1
    maxReplicas: 2
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization
    - type: Resource
      resource:
        name: memory
        target:
          averageUtilization: 80
          type: Utilization