apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-nsfw
  namespace: main
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: environment
                operator: In
                values:
                - test
