apiVersion: v1
kind: Service
metadata:
  name: minio-lb
  namespace: minio
spec:
  loadBalancerIP: 172.31.58.14
  externalIPs:
    - 172.31.58.14
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: minio
    release: minio
  type: LoadBalancer
