apiVersion: v1
kind: Service
metadata:
  name: thanos-store-gateway-lb
  namespace: monitoring
spec:
  loadBalancerIP: 172.31.59.36
  externalIPs:
    - 172.31.59.36
  ports:
  - name: grpc
    port: 10901
    protocol: TCP
    targetPort: grpc
  selector:
    thanos-store-api: "true"
  type: LoadBalancer
