---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-nsfw-svc
  namespace: main
spec:
  selector:
    app.kubernetes.io/name: chatbot-nsfw
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
