---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-rasa-svc
  namespace: main
spec:
  selector:
    app.kubernetes.io/name: chatbot-rasa
  ports:
    - name: http
      protocol: TCP
      port: 5005
      targetPort: 5005
