apiVersion: v1
kind: Service
metadata:
  labels:
    app: thanos-receive
    part-of: thanos
  name: thanos-receive
  namespace: monitoring
spec:
  ports:
  - name: grpc
    port: 10901
    targetPort: 10901
  - name: http
    port: 10902
    targetPort: 10902
  - name: remote-write
    port: 19291
    targetPort: 19291
  selector:
    app: thanos-receive
      #tenant: a
      #controller.receive.thanos.io: thanos-receive-controller
      # controller.receive.thanos.io/hashring: tenant-a
      #controller.receive.thanos.io/hashring: tenant-b
      #tenant: b  
      #part-of: thanos
