global:
   resolve_timeout: 5m

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal:
      - alertname
      - cluster
      - namespace

route:
  receiver: 'default'
  group_by: ['alertname','cluster']
  group_wait: 5s
  group_interval: 6m
  repeat_interval: 6h

  routes:
  - match:
      cluster: "production"
      namespace: "monitoring"
    receiver: 'monitoring'    
  - match:
      type: "os-metrics"
    receiver: 'operationsystem'       
  - match:
      type: "monitoring-metrics"
    receiver: 'monitoring'
  - match:
      kubernetes_namespace: "develop"
    receiver: 'develop'   
  - match:
      kubernetes_namespace: "test"
    receiver: 'test'       
      

receivers:
- name: 'default'
- name: monitoring
  slack_configs:
    - api_url: https://chat.tapsi.shop/hooks/ejeh1ig7m3guxj9sstutftakwo
      send_resolved: true
      http_config:
        follow_redirects: true
        enable_http2: true
      text: >-
        {{ if eq .Status "firing" -}}
        {{ range .Alerts -}} *Alert severity:* `{{ .Labels.severity }}`
        *Description:* {{ .Annotations.description }} 
        *Summary:* {{ .Annotations.summary }} 
        {{ end }}
        {{- else if eq .Status "resolved" -}}
        {{ range .Alerts -}} *Alert severity:* `{{ .Labels.severity }}`
        *Description:* {{ .Annotations.resolved }} 
        {{ end }}
        {{ end }}
      title: >-
        [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{
        .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname
        }}         

- name: develop
  slack_configs:
    - api_url: https://chat.tapsi.shop/hooks/wrpsz3fywpyu3ergt9bu83hk9w
      send_resolved: true
      text: >-
        {{ if eq .Status "firing" -}}
        {{ range .Alerts -}} *Alert severity:* `{{ .Labels.severity }}`
        *Description:* {{ .Annotations.description }} 
        *Summary:* {{ .Annotations.summary }} 
        {{ end }}
        {{- else if eq .Status "resolved" -}}
        {{ range .Alerts -}} 
        *Alert severity:* `{{ .Labels.severity }}`
        *Description:* {{ .Annotations.resolved }}
        {{- "\n" -}} 
        {{ end }}
        {{ end }}
      title: >-
        [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{
        .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname
        }}   

- name: test
  slack_configs:
    - api_url: https://chat.tapsi.shop/hooks/n65shtck1trsjcxqcger8ikdio
      send_resolved: true
      text: >-
        {{ if eq .Status "firing" -}}
        {{ range .Alerts -}} *Alert severity:* `{{ .Labels.severity }}`
        *Description:* {{ .Annotations.description }} 
        *Summary:* {{ .Annotations.summary }} 
        {{ end }}
        {{- else if eq .Status "resolved" -}}
        {{ range .Alerts -}} 
        *Alert severity:* `{{ .Labels.severity }}`
        *Description:* {{ .Annotations.resolved }}
        {{- "\n" -}} 
        {{ end }}
        {{ end }}
      title: >-
        [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{
        .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname
        }}                    

- name: operationsystem
  slack_configs:
    - api_url: https://chat.tapsi.shop/hooks/mheutu4i5jr1igo46cagwdxe7h
      send_resolved: true
      http_config:
        follow_redirects: true
        enable_http2: true
      text: >-
        {{ if eq .Status "firing" -}}
        {{ range .Alerts -}} *Alert severity:* `{{ .Labels.severity }}`
        *Description:* {{ .Annotations.description }} 
        *Summary:* {{ .Annotations.summary }} 
        {{ end }}
        {{- else if eq .Status "resolved" -}}
        {{ range .Alerts -}} *Alert severity:* `{{ .Labels.severity }}`
        *Description:* {{ .Annotations.resolved }} 
        {{ end }}
        {{ end }}
      title: >-
        [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{
        .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname
        }}    
