apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: main
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: environment
                operator: In
                values:
                - stage
        
