FROM mcr-fr.nullip.ir/dotnet/sdk:9.0-noble 
RUN apt-get update -y && \
    apt-get install -yq tzdata curl && \
    ln -fs /usr/share/zoneinfo/Asia/Tehran /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
ENV TZ="Asia/Tehran"