FROM  docker.hasti.co/dotnet/sdk:9.0 AS build
ARG CSPROJECT
WORKDIR /src
COPY . .
ADD ./nuget.config  ~/.nuget/NuGet/nuget.config
RUN dotnet restore --disable-parallel --configfile=~/.nuget/NuGet/nuget.config "${CSPROJECT}"
RUN dotnet publish "${CSPROJECT}" -c Release -o /app/publish --no-restore


FROM docker.hasti.co/dotnet/aspnet:9.0 AS run
ARG PROJECT
ENV EXE="${PROJECT}.dll"
ENV ASPNETCORE_HTTP_PORTS="80"
ARG CONSULKEYS
ARG CONSULSERVER
ARG CONSULTOKEN
ENV Consul__Keys=$CONSULKEYS
ENV Consul__Server=$CONSULSERVER
ENV Consul__Token=$CONSULTOKEN
WORKDIR /app
EXPOSE 80
COPY --from=build /app/publish .
ENTRYPOINT dotnet "$EXE"