apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-search
  namespace: iplus
spec:
  ingressClassName: nginx
  rules:
  - host: apisearch.dartil.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-search
            port:
              number: 3001