---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: data-receiver-2
    namespace: monitoring
spec:
    accessModes:
    - ReadWriteOnce
    storageClassName: longhorn
    resources:
      requests:
        storage: 25000Mi
    volumeMode: Filesystem

