apiVersion: v1
kind: Secret
metadata:
  namespace: monitoring
  name: alertmanager-main
type: Opaque
stringData:
  alertmanager.yaml: |-
     global:
       resolve_timeout: 1m
       slack_api_url: 'https://chat.dc.afranet.co/hooks/656dd8bd72f265d79c866dc3/qvKueW7H2fT77793sWb7SE6i7tCarTn87NuxjoWxhZvg9zRE'
     route:
       receiver: 'notifications'
     
     receivers:
     - name: 'notifications'
       slack_configs:
       - send_resolved: true
         icon_url: https://avatars3.githubusercontent.com/u/3380462
         title: |-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
          {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
            {{" "}}(
            {{- with .CommonLabels.Remove .GroupLabels.Names }}
              {{- range $index, $label := .SortedPairs -}}
                {{ if $index }}, {{ end }}
                {{- $label.Name }}="{{ $label.Value -}}"
              {{- end }}
            {{- end -}}
            )
          {{- end }}
         text: >-
          {{ range .Alerts -}}
          *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

          *Description:* {{ .Annotations.description }}

          *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
