apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: develop
  name: maintenance-page
  labels:
    app.kubernetes.io/name: maintenance-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: maintenance-page
  template:
    metadata:
      labels:
        app.kubernetes.io/name: maintenance-page
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: "app.kubernetes.io/name"
                  operator: In
                  values:
                    - maintenance-page
              topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: environment
                operator: In
                values:
                - test    
      imagePullSecrets:
        - name: hasti-docker-repo
      containers:
      - name: nginx
        image: docker.hasti.co/library/nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        # Because no subPath is specified, all keys in configmap willb
        # be mounted as files at the specified mountPath
        - name: config-volume
          mountPath: /usr/share/nginx/html/maintenance/
        - name: config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        resources:
            requests:
              memory: "0.5Gi"
              cpu: "0.1"
            limits:
              memory: "1Gi"
              cpu: "1"
      volumes:
        - name: config-volume
          configMap:
            name: maintenance-image
---
apiVersion: v1
kind: Service
metadata:
  namespace: develop
  name: maintenance-page
spec:
  selector:
    app.kubernetes.io/name: maintenance-page
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80