apiVersion: apps/v1
kind: Deployment
metadata:
  name: internalservicegw
  namespace: develop
  labels:
    image-tag: "20250308.1"
    app.kubernetes.io/name: internalservicegw
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: internalservicegw
  template:
    metadata:
      labels:
        app.kubernetes.io/name: internalservicegw
        image-tag: "20250308.1"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: "app.kubernetes.io/name"
                  operator: In
                  values:
                    - internalservicegw
              topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: environment
                operator: In
                values:
                - test
      restartPolicy: Always
      imagePullSecrets:
        - name: hasti-docker-repo
      containers:
        - image: docker.hasti.co/hastim/internalservicegw:20250308.1
          name: internalservicegw
          command: ["dotnet", "HIT.Hastim.Gateway.InternalServices.Web.dll"]
          envFrom:
            - configMapRef:
                name: internalservicegw
          ports:
            - containerPort: 80
              name: api
              protocol: TCP
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "0.5Gi"
              cpu: "0.1"
            limits:
              memory: "2Gi"
              cpu: "1"
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /hc/live
              port: api
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /hc/live
              port: api
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5