apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-gateway
  namespace: main
  labels:
    app.kubernetes.io/name: chatbot-gateway
  annotations:
    configmap.reloader.stakater.com/reload: "gw-configmap"  
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: chatbot-gateway
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chatbot-gateway
    spec:
      imagePullSecrets:
        - name: hasti-docker-repo
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: "app.kubernetes.io/name"
                  operator: In
                  values:
                    - chatbot-gateway
              topologyKey: "kubernetes.io/hostname"    
      containers:
        - image: example-image #docker.hasti.co/alpha/chatbot-gateway:test
          imagePullPolicy: IfNotPresent
          name: chatbot-gateway
          envFrom:
            - configMapRef:
                name: gw-configmap
          resources:
            requests:
              memory: "0.5Gi"
              cpu: "0.1"
            limits:
              memory: "2Gi"
              cpu: "1"
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            runAsUser: 10001
            capabilities:
              drop: 
                - all   
      restartPolicy: Always
