apiVersion: v1
data:
  AWS_ACCESS_KEY: U3kybU92TEJVdTBudFp0UQ==
  AWS_HOST: aHR0cDovL21pbmlvLm1pbmlvLnN2Yy5jbHVzdGVyLmxvY2FsOjkwMDAK
  AWS_SECRET_KEY: WlRncWR1SVhjWHdlaDdNSGRBeG03enBtZ1hKNG9Xc1o=
kind: Secret
metadata:
  name: s3-secrets
  namespace: stage
type: Opaque
