{{- if .Values.thanos.store.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-store-gateway
  namespace: {{ .Values.namespace }}
  labels:
    app: thanos-store-gateway
spec:
  replicas: {{ .Values.thanos.store.replicas }}
  selector:
    matchLabels:
      app: thanos-store-gateway
      thanos-store-api: "true"
  serviceName: thanos-store-gateway
  template:
    metadata:
      labels:
        app: thanos-store-gateway
        thanos-store-api: "true"
    spec:
      containers:
        - name: thanos
          image: {{ .Values.thanos.image }}
          args:
          - store
          - --grpc-address=0.0.0.0:10901
          - --http-address=0.0.0.0:10902
          - --data-dir=/data
          - "--objstore.config=$(S3_APPLICATION_CREDENTIALS)"        
           # Memory optimization settings
          - "--index-cache-size=512MB"
          - "--chunk-pool-size=512MB"
          - "--store.grpc.series-sample-limit=50000000"
          - "--store.grpc.series-max-concurrency=20"
          - "--min-time=-30d"  
          - "--max-time=9999-12-31T23:59:59Z"  
          # Performance tuning          
          - "--store.caching-bucket.config=type: IN-MEMORY" 
          env:
            - name: S3_APPLICATION_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  key: thanos-s3-credentials.yaml
                  name: thanos-s3-credentials
          ports:
          - name: http
            containerPort: 10902
          - name: grpc
            containerPort: 10901
          resources:
            {{- toYaml .Values.thanos.store.resources | nindent 12 }}
          livenessProbe:
            failureThreshold: 4
            httpGet:
              path: /-/healthy
              port: 10902
              scheme: HTTP
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 10902
              scheme: HTTP
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - name: data
              mountPath: /data          
            - name: thanos-s3-credentials
              mountPath: /etc/secret
              readOnly: false
            - name: timezone-volume
              mountPath: /etc/timezone
              readOnly: true
            - name: localtime-volume
              mountPath: /etc/localtime
              readOnly: true               
      volumes:
        - name: data
          emptyDir: {}
        - name: thanos-s3-credentials
          secret:
            secretName: thanos-s3-credentials
        - name: timezone-volume
          hostPath:
            path: /etc/timezone
            type: File
        - name: localtime-volume
          hostPath:
            path: /etc/localtime
            type: File

             
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-store-gateway
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: grpc
      port: 10901
      targetPort: grpc
  selector:
    thanos-store-api: "true"
{{- end }}
