apiVersion: apps/v1
kind: Deployment
metadata:
  name: statemachine-webapi
  namespace: develop
  labels:
    image-tag: "20250826.2"
    app.kubernetes.io/name: statemachine-webapi
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: statemachine-webapi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: statemachine-webapi
        image-tag: "20250826.2"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: "app.kubernetes.io/name"
                  operator: In
                  values:
                    - statemachine-webapi
              topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: environment
                operator: In
                values:
                - test
      restartPolicy: Always
      imagePullSecrets:
        - name: hasti-docker-repo
      containers:
        - image: docker.hasti.co/hastim/statemachine_webapi:20250826.2
          name: statemachine-webapi
          command: ["dotnet", "HIT.Hastim.StateMachine.Endpoints.WebApi.dll"]
          envFrom:
            - configMapRef:
                name: statemachine-webapi
          ports:
            - containerPort: 80
              name: api
              protocol: TCP
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "0.5Gi"
              cpu: "0.1"
            limits:
              memory: "2Gi"
              cpu: "1"