apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-admin
  namespace: develop
  labels:
    app.kubernetes.io/name: frontend-admin
    image-tag: "20250909.2"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend-admin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend-admin
        image-tag: "20250909.2"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - frontend-admin
              topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: environment
                operator: In
                values:
                - test
      restartPolicy: Always
      imagePullSecrets:
        - name: hasti-docker-repo
      containers:
        - image: docker.hasti.co/frontend/admin:20250909.2
          name: frontend-admin
          ports:
            - containerPort: 4000
              name: api
              protocol: TCP
          command: ["node", "/app/node_modules/nx/bin/nx.js", "serve", "admin", "--configuration=production", "--hostname", "0.0.0.0", "--port", "4000", "--verbose"]
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "0.5Gi"
              cpu: "0.5"
            limits:
              memory: "3Gi"
              cpu: "2"
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /api/health/status/
              port: api
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /api/health/status/
              port: api
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
