apiVersion: v1
kind: Service
metadata:
  name: frontend-admin
  namespace: develop
spec:
  ports:
    - port: 80
      targetPort: 4000
      name: api
  selector:
    app.kubernetes.io/name: frontend-admin