---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-hasti-sentiment-svc
  namespace: main
spec:
  selector:
    app.kubernetes.io/name: chatbot-hasti-sentiment
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
